on:
  workflow_dispatch:
  push:
    paths-ignore:
      - docs
    branches:
      - main
name: release
permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
      - name: generate changelog for new tag
        uses: orhun/git-cliff-action@v4.5.1
        id: git-cliff
        with:
          config: .github/cliff.toml
          args: --strip header --tag ${{ steps.tag.outputs.new_tag }}
        env:
          OUTPUT: docs/changelog.md
          GITHUB_REPO: ${{ github.repository }}
      - name: commit
        run: |
          git config --global user.name "mateothegreat"
          git config --global user.email "matthew@matthewdavis.io"
          git add .
          git commit -am "release: update changelog and bumping version"
          git push origin HEAD:main
      - name: create github release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.git-cliff.outputs.content }}
          tag_name: ${{ steps.tag.outputs.new_tag }}
          files: replace
  notify:
    if: always()
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          status: ${{ needs.build.result }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
